# Generated by Django 5.0.6 on 2024-06-08 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_user_user_role'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('team', 'theme')},
        ),
    ]
