# Generated by Django 5.0.6 on 2024-06-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_lesson_assigments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='assigments_status',
            field=models.BooleanField(default=False),
        ),
    ]
