# Generated by Django 5.0.6 on 2024-06-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_exercise'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('student', 'lesson')},
        ),
    ]
