# Generated by Django 5.0.6 on 2024-06-08 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_user_user_role'),
        ('students', '0006_alter_exercise_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='blog.student'),
        ),
    ]
