# Generated by Django 5.0.6 on 2024-06-13 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_user_user_role'),
        ('students', '0007_alter_exercise_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='blog.team'),
        ),
    ]
